language: python
services:
  - rabbitmq
python:
  - '3.5'
sudo: false
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - python setup.py install
script: python setup.py test --slowest
